<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => 'Токен доступа',
    'Active' => 'Активный',
    'An email has been sent with instructions for password reset' => 'Инструкции по восстановлению пароля отправлены на email',
    'An email has been sent with instructions for resetting your password' => 'Инструкции для восстановления пароля отправлены на email',
    'Are you sure you want to delete this item?' => 'Вы уверены что хотите удалить этот элемент?',
    'Attributes' => 'Атрибуты',
    'Auth code not found or expired!' => 'Код подлинности не найден или просрочен!',
    'Change password' => 'Изменить пароль',
    'Code' => 'Код',
    'Confirmation code not found or expired!' => 'Код подтверждения не найден или просрочен!',
    'Confirmation mail has been sent to {0}.' => 'Письмо с подтверждением было отправлено на {0}.',
    'Continue' => 'Продолжить',
    'Create' => 'Создать',
    'Create a new one!' => 'Создать новый!',
    'Create {modelClass}' => 'Создать {modelClass}',
    'Created At' => 'Создан',
    'Delete' => 'Удалить',
    'Deleted' => 'Удален',
    'Don\'t have an account yet? Sign up!' => 'Ещё нет аккаунта? Зарегистрируйтесь!',
    'Email' => 'Электронная почта',
    'Error while confirming your account!' => 'Ошибка при подтверждении вашего аккаунта!',
    'Error while deleting the account!' => 'Ошибка при удалении аккаунта!',
    'Error while trying to confirm the user!' => 'Ошибка при попытке подтвердить пользователя!',
    'Expires' => 'Истекает',
    'Expires On' => 'Истекает',
    'Forgot password?' => 'Забыли пароль?',
    'ID' => 'ID',
    'Incorrect email or password.' => 'Неверный email или пароль.',
    'Incorrect username or password.' => 'Неверное имя пользователя или пароль.',
    'Link accounts' => 'Связать аккаунты',
    'Login' => 'Войти',
    'New password' => 'Новый пароль',
    'New password repeat' => 'Повторить новый пароль',
    'Old password' => 'Старый пароль',
    'One more step' => 'Ещё один шаг',
    'Password' => 'Пароль',
    'Passwords must not be the same!' => 'Пароли не должны быть одинаковы!',
    'Please enter the user\'s email address:' => 'Пожалуйста, введите email пользователя:',
    'Please fix following errors:' => 'Пожалуйста исправьте следующие ошибки:',
    'Profile' => 'Профиль',
    'Provider' => 'Провайдер',
    'Recover your password' => 'Восстановите ваш пароль',
    'Recovery message sent' => 'Сообщение восстановления отослано',
    'Registration confirmed' => 'Регистрация подтверждена!',
    'Registration disabled!' => 'Регистрация отключена!',
    'Reset' => 'Сброс',
    'Search' => 'Поиск',
    'Signup' => 'Зарегистрироваться',
    'Submit' => 'Отправить',
    'Successfully created user!' => 'Пользователь успешно создан!',
    'The combination of User ID, Code and Type has already been taken.' => 'Такая комбинация идентификатора пользователя, кода и типа уже существует.',
    'The new passwords are not the same.' => 'Новые пароли не одинаковы.',
    'The requested page does not exist.' => 'Запрошенная страница не существует.',
    'The system requires a password change' => 'Система требует смены пароля',
    'The user is successfuly confirmed!' => 'Пользователь успешно подтвержден!',
    'There is no user with this email address' => 'Нет пользователя с таким адресом электронной почты',
    'This email address has already been taken.' => 'Этот адрес электронной почты уже занят.',
    'Token Create Time' => 'Время создания токена',
    'Token not found!' => 'Токен не найден!',
    'Type' => 'Тип',
    'Unconfirmed account are not allowed to login' => 'Нельзя войти в неподтвержденный аккаунт',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить {modelClass}: ',
    'Updated At' => 'Обновлен',
    'User ID' => 'ID пользователя',
    'User not found!' => 'Пользователь не найден!',
    'User successfuly deleted!' => 'Пользователь успешно удален!',
    'User successfuly locked!' => 'Пользователь успешно заблокирован!',
    'Users' => 'Пользователи',
    'You need to confirm your email address' => 'Вам необходимо подтвердить ваш адрес электронной почты',
    'Your account is locked!' => 'Ваш аккаунт заблокирован!',
    'Your account was successfuly confirmed!' => 'Ваш аккаунт был успешно подтвержден!',
    'Your password is the same as a previous password of yours. For security reasons, please add another password.' => 'Ваш пароль такой же как предыдущий. По причинам безопасности, пожалуйста добавьте другой пароль.',
    'Your registration is confirmed succesfully!' => 'Ваша регистрация успешно подтверждена!',
    '{attribute} must be a string' => 'Атрибут {attribute} должен быть строкой',
    'Username' => 'Имя пользователя',
    'Remember Me' => 'Запомнить меня',
];
